// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJnAO8BNNCutlvH8HP8e0uhG80I0ervNo',
    appId: '1:699613484476:web:d3c3e19b4b8561b5a2c7b9',
    messagingSenderId: '699613484476',
    projectId: 'quick-bite-270f8',
    authDomain: 'quick-bite-270f8.firebaseapp.com',
    storageBucket: 'quick-bite-270f8.firebasestorage.app',
    measurementId: 'G-2K1EKNPBFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYbAcSkIUGax8mh2FPkH45D1uKYvlxbLo',
    appId: '1:699613484476:android:38a8004b37c53dc0a2c7b9',
    messagingSenderId: '699613484476',
    projectId: 'quick-bite-270f8',
    storageBucket: 'quick-bite-270f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0ZKhVZmqWQlLHf1ezeNCcnsXoSgR6Qk',
    appId: '1:699613484476:ios:321f7739356aa472a2c7b9',
    messagingSenderId: '699613484476',
    projectId: 'quick-bite-270f8',
    storageBucket: 'quick-bite-270f8.firebasestorage.app',
    iosBundleId: 'com.example.quickBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0ZKhVZmqWQlLHf1ezeNCcnsXoSgR6Qk',
    appId: '1:699613484476:ios:321f7739356aa472a2c7b9',
    messagingSenderId: '699613484476',
    projectId: 'quick-bite-270f8',
    storageBucket: 'quick-bite-270f8.firebasestorage.app',
    iosBundleId: 'com.example.quickBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJnAO8BNNCutlvH8HP8e0uhG80I0ervNo',
    appId: '1:699613484476:web:6cdfb47d99a346eaa2c7b9',
    messagingSenderId: '699613484476',
    projectId: 'quick-bite-270f8',
    authDomain: 'quick-bite-270f8.firebaseapp.com',
    storageBucket: 'quick-bite-270f8.firebasestorage.app',
    measurementId: 'G-BH5M1NEBG2',
  );
}
